version: '3.1'

services: 

  cassandra-seed:
    container_name: cassandra-seed
    hostname: cassandra-seed
    image: cassandra:latest
    ports:
      - "9042:9042"   # Native transport
      - "7199:7199"   # JMX
      - "9160:9160"   # Thrift clients
      - "7001:7001"   # cluster communication (SSL)
      - "7000:7000"   # cluster communication 
    environment:     
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=password123
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_RACK=cassandra-rack
    # volumes:
      # - 'cassandra_yaml:/usr/share/engaze/cassandra/conf/cassandra.yaml:ro'
      # - 'cassandra:/usr/share/engaze/cassandra'
    networks:
      - engaze-network
      
  cassandra-node-1:
    image: cassandra:latest
    #restart: always
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 120 && /docker-entrypoint.sh cassandra -f"
    hostname: cassandra-node-1
    container_name: cassandra-node-1
    
    environment:
      - CASSANDRA_SEEDS=cassandra-seed
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_RACK=cassandra-rack
    links:
    - cassandra-seed
    
    depends_on:
      - cassandra-seed
    
    # volumes:
      # - 'cassandra_yaml:/usr/share/engaze/cassandra/conf/cassandra.yaml:ro'
      # - 'cassandra:/usr/share/engaze/cassandra'
    networks:
      - engaze-network
   
  cassandra-node-2:
    image: cassandra:latest
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 120 && /docker-entrypoint.sh cassandra -f"
    #restart: always
    hostname: cassandra-node-2
    container_name: cassandra-node-2
    
    links:
    - cassandra-seed
     
    environment:
      - CASSANDRA_SEEDS=cassandra-seed
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_RACK=cassandra-rack
      
    depends_on:
      - cassandra-seed
      
    # volumes:
      # - 'cassandra_yaml:/usr/share/engaze/cassandra/conf/cassandra.yaml:ro'
      # - 'cassandra:/usr/share/engaze/cassandra'
    networks:
      - engaze-network      
  
networks:
  engaze-network:
    external:
      name: engaze-network
    